---
title: "Distributed sensor measurements next level"
layout: post
summary: Extended sensor control and visualization based on MQTT
tags:
  - hardware
  - raspberrypi
  - circuitpython
date: 2024-07-18
---

= Distributed sensor mesurements next level

NOTE: This article is still work in progress!

The initial project described in xref:Distributed measurements.md[Distributed measurements] had some shortcomings:

* No easy access to data of other measurement locations. This is required if you want to implement a dew point controlled ventilation.

* Maintaining the RaspberryPis was quite some effort. In the end most of the measurement locations have been updated to use RaspberryPi Zero Ws which were pretty stable, but the OS still needed to be managed (Using link:https://saltproject.io/[Salt] helped to keep them up to date, but there were still some manual steps and time involved to set up replacement systems.)

== Ideas for moving next level

* Use embedded systems for measurements
** Use less power
** Should be easier to replace/scale
** But: We don't want to reimplement the software
* Use standardised communication protocol, to become independent from the already outdated InfluxDB 1.8
** MQTT seems to be a good choice
** Simple integration with OpenHAB should be possible
** Supports subscribing to other sensor's data from everywhere.

== Hardware selection

After some research and as we were already using the link:https://github.com/adafruit/circuitpython[Adafruit Circuitpython] drivers in the RaspberryPi implementation we ordered a bunch of link:https://learn.adafruit.com/adafruit-qt-py-esp32-s2[Adafruit QT Py ESP32-S2] and to get started with. For now there is a separate project link:https://github.com/wuan/circuitpy-logger[] to get started, but we will integrate with the existing link:https://github.com/wuan/klimalogger[] as a future refactoring. Most of the codebase is already identical.

After some weeks of testing the ESP32 modules are now running quite stable and usually have no problem with repeated power outages. The modules are easily configurable with a simple configuration file

[source]
----
WIFI_SSID = "SSDF"
WIFI_PASSWORD = "XZCXCZXC"
MQTT_HOST="mqtt"
MQTT_PREFIX="sensors/test"
ELEVATION="530"
----

and installing the newest software is automated by using the `./install.py` script.

For places with bad WLAN reception there is a version of the ESP32 board which can use an external WLAN antenna but in the end the setup is much more easy to maintain compared to the RaspberryPi version we used before (Some of the old RasberryPis are still in use and the `klimalogger` package has been updated to be able to use MQTT for data delivery as well).

== Missing software components

=== MQTT to time series database

Component to store data from MQTT into a timeseries database.

We updated to link:https://docs.influxdata.com/influxdb/v2/[InfluxDB 2] but also setup an evaluation system with link:https://www.timescale.com/[Timescale]. For now we keep using InfluxDB as the Grafana integration for Timescale seemed not up to the level we have reached with InfluxDB.

In order to put all the data being distributed via MQTT to those time series targets we created a separate compontent link:https://github.com/wuan/mqtt-gateway[] which uses link:https://www.rust-lang.org/[Rust] as a programming language which should be a good fit for a reliable and performant bridge service.

In order to have time series data from other components like shelly relays, plugs and switches or our OpenDTU based receiver for our photovoltaic microinverter we added support and a configuration file base flexibility to the project.

=== Integration with OpenHAB

In order to use sensor data for tasks like fan control we also started to integrate the MQTT data with the local running OpenHAB server
